import { portfolio, projects } from '@/data/portfolio';
import { Navigation } from '@/components/navigation';
import { Section } from '@/components/section';
import { SocialLinks } from '@/components/social-links';
import { ProjectGallery } from '@/components/project-gallery';
import { ContactForm } from '@/components/contact-form';
import { EngineeringJourney } from '@/components/engineering-journey';
import { EloquenceCard } from '@/components/eloquence-card';
export default function Home() {
  const url = process.env.NEXT_PUBLIC_SITE_URL;
  const person = { '@context': 'https://schema.org', '@type': 'Person', name: portfolio.name, description: portfolio.title, ...(url ? { url } : {}), affiliation: { '@type': 'CollegeOrUniversity', name: portfolio.school }, knowsAbout: ['Java', 'Python', 'SQL', 'Git', 'Linux', 'Gestion de projet', 'Microsoft Project'], sameAs: [portfolio.contact.linkedin, portfolio.contact.github].filter(Boolean) };
  return <><Navigation /><main id="contenu">
    <section id="accueil" className="hero wrap"><div className="hero-copy"><p className="availability"><span />{portfolio.availability}</p><p className="eyebrow">{portfolio.title}</p><h1 className="identity-heading">Rayan<br /><span>Minlang.</span></h1><p className="professional-headline">{portfolio.headline}</p><p className="hero-description">{portfolio.intro}</p><div className="hero-actions"><a href="#contact" className="button primary">Proposer une alternance <span>↗</span></a><a href="#projets" className="button secondary">Voir le code et les projets <span>↓</span></a></div><SocialLinks /></div>
    <aside className="recruiter-card" aria-label="Profil en bref"><p className="eyebrow">PROFIL EN BREF</p><div className="profile-monogram" aria-hidden="true">RM<span>2026 — 2029 / 3iL</span></div><dl><div><dt>Formation</dt><dd>Cycle ingénieur informatique</dd></div><div><dt>Base technique</dt><dd>Java · Python · C · SQL · Git</dd></div><div><dt>Compétence complémentaire</dt><dd>Gestion de projet · Microsoft Project</dd></div><div><dt>Cap professionnel</dt><dd>Spécialisation IA & Data</dd></div></dl><a className="text-link" href={`mailto:${portfolio.contact.email}`}>{portfolio.contact.email}<span>↗</span></a></aside>
    <div className="hero-foot"><p>« {portfolio.mantra} »</p><a href="#engineering-journey">Engineering Journey ↓</a></div></section>
    <Section id="engineering-journey" number="01" eyebrow="Engineering Journey" title="Une progression, avec un cap clair."><EngineeringJourney /><p className="small-note">Les étapes IA & Data et Project Leadership sont des objectifs futurs. Software Engineering représente des compétences en développement.</p></Section>
    <Section id="apropos" number="02" eyebrow="À propos" title="Relier le développement à la conduite de projet."><div className="about-grid"><p className="large-copy">Résoudre un problème.<br />Structurer une solution.<br /><span>Travailler en équipe.</span></p><div><p>{portfolio.bio}</p><p>{portfolio.ambition}</p></div></div></Section>
    <Section id="competences" number="03" eyebrow="Compétences" title="Le socle technique et les méthodes de travail."><div className="skill-grid">{portfolio.skills.map(skill => <article className="skill-card" key={skill.title}><span className="card-number">{skill.icon}</span><h3>{skill.title}</h3><p>{skill.description}</p><div className="tags">{skill.items.map(item => <span key={item}>{item}</span>)}</div>{'note' in skill && <p className="small-note">{skill.note}</p>}</article>)}</div></Section>
    <Section id="projets" number="04" eyebrow="Projets & code" title="Des réalisations consultables."><ProjectGallery /></Section>
    <Section id="parcours" number="05" eyebrow="Formation" title="Un parcours scientifique et informatique."><div className="timeline">{portfolio.education.filter(item => item.status === 'Formation actuelle' || item.status === 'Formation précédente').map(item => <article key={item.title}><div className="timeline-date">{item.date.includes('dates à préciser') ? 'Deux années de prépa' : item.date}</div><div className="timeline-content"><p className="eyebrow">{item.status}</p><h3>{item.title}</h3><p className="organization">{item.organization}</p><p>{item.description}</p></div></article>)}</div></Section>
    <Section id="gestion" number="06" eyebrow="Gestion de projet" title="Planifier, coordonner, suivre."><div className="management-grid"><div><p>{portfolio.management.intro}</p><div id="certifications" className="certification-summary"><p className="eyebrow">CERTIFICATION ACQUISE</p><h3>Gestion de projet</h3><p>Planification, ordonnancement, ressources et suivi d’avancement.</p><small>Organisme, date et justificatif : informations à compléter.</small></div><h3>Microsoft Project</h3><p>Formation pratique à la création de plannings, aux dépendances et au suivi des échéances.</p></div><div className="process">{portfolio.management.steps.map((step, index) => <div key={step}><span>0{index + 1}</span><h3>{step}</h3><span aria-hidden="true">↗</span></div>)}</div></div></Section>
    <Section id="entrepreneuriat" number="07" eyebrow="Initiatives" title="Entrepreneuriat, communication et collectif."><div className="venture-grid">{projects.filter(p => p.category === 'Entrepreneurship').map(p => <article key={p.id}><span className="venture-index">CONCEPT EN RÉFLEXION</span><h3>{p.name}</h3><p>Initiative entrepreneuriale au stade conceptuel. Périmètre et proposition de valeur en cours de définition.</p></article>)}</div><EloquenceCard /><div id="activites" className="activity-grid compact-activities">{portfolio.activities.map(item => <article key={item.title}><h3>{item.title}</h3><p>{item.text}</p></article>)}</div></Section>
    <section id="alternance" className="opportunity wrap"><div><p className="eyebrow"><span className="status-dot" /> RECHERCHE D’ALTERNANCE</p><h2>Contribuer à votre équipe.<br /><span>Progresser sur le terrain.</span></h2><p>{portfolio.opportunity.description}</p><p className="small-note">{portfolio.opportunity.rhythm}</p><a className="button primary" href={`mailto:${portfolio.contact.email}?subject=Opportunit%C3%A9%20d%27alternance`}>Me contacter directement <span>↗</span></a></div><div className="opportunity-details"><p className="eyebrow">DOMAINES RECHERCHÉS</p>{portfolio.opportunity.domains.map((domain, index) => <div key={domain}><span>0{index + 1}</span>{domain}</div>)}<SocialLinks includeCv /></div></section>
    <Section id="contact" number="08" eyebrow="Contact" title="Échangeons sur votre opportunité."><div className="contact-grid"><div><p>Vous recherchez un alternant en développement logiciel ou souhaitez échanger sur mon parcours ? Contactez-moi par email ou sur LinkedIn.</p><p className="contact-name">{portfolio.name}<span>{portfolio.title}</span></p><a className="contact-email" href={`mailto:${portfolio.contact.email}`}>{portfolio.contact.email}</a><SocialLinks includeCv /></div><ContactForm /></div></Section>
  </main><footer className="footer wrap"><a className="brand" href="#accueil">{portfolio.initials}<span>.</span></a><p>© {new Date().getFullYear()} {portfolio.name}</p><p><span className="status-dot" /> Recherche d’alternance</p><a href="#accueil">Retour en haut ↑</a></footer><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(person).replace(/</g, '\u003c') }} /></>;
}
